# Generated by Django 4.2.5 on 2024-12-01 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('state', models.CharField(max_length=100)),
                ('gst_number', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True)),
                ('date_of_billing', models.DateField(default=django.utils.timezone.now)),
                ('invoice_number', models.CharField(max_length=20, unique=True)),
                ('date_of_collection', models.DateField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_gst', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_cgst', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True)),
                ('total_sgst', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True)),
                ('total_igst', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='panelapi.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=255)),
                ('company_owned', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('owner_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('rate_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hsn_sac_code', models.CharField(blank=True, max_length=20, null=True)),
                ('outlets', models.ManyToManyField(related_name='products', to='panelapi.outlet')),
            ],
        ),
        migrations.CreateModel(
            name='OutletCreds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='panelapi.outlet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlet_creds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='panelapi.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='panelapi.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='panelapi.outlet'),
        ),
    ]
