# Generated by Django 4.2.5 on 2024-12-01 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panelapi', '0003_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='outlet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='panelapi.outlet'),
            preserve_default=False,
        ),
    ]
