# Generated by Django 4.2.5 on 2024-12-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panelapi', '0005_order_mode_of_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_after_gst',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True),
        ),
    ]
