# Generated by Django 4.2.5 on 2024-12-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panelapi', '0008_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='reference',
            field=models.TextField(blank=True, null=True),
        ),
    ]
