# Generated by Django 4.2.5 on 2025-01-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panelapi', '0009_customer_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='outletcreds',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
