# Generated by Django 4.2.5 on 2025-01-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panelapi', '0010_outletcreds_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='outletcreds',
            name='role',
            field=models.CharField(choices=[('Counter Operator', 'Counter Operator'), ('Shop Owner', 'Shop Owner')], default='Shop Owner', max_length=50),
        ),
    ]
