# Generated by Django 4.2.5 on 2025-01-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panelapi', '0011_outletcreds_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='hanger',
            field=models.BooleanField(default=False),
        ),
    ]
