# Generated by Django 5.2.11 on 2026-03-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panelapi', '0015_orderitemspecification_orderitem_specification'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='gst_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
